server:
  port: 8081

app:
  default:
    max-free-accounts: 5

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-service
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5432/dms_project
    username: postgres
    password: Suchang0-
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true